name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    permissions:
      contents: read       # Need to read contents (checkout code)
      packages: write      # Need to write packages (push Docker image)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta # Give this step an ID to reference its outputs
        uses: docker/metadata-action@v5
        with:
          images: sagabillpro/saga_main # IMPORTANT: Replace with your Docker Hub username and repo name
          tags: |
            # Tag with the Git tag on release events
            type=ref,event=release
            # Tag with 'latest' on pushes to the default branch (main)
            type=raw,value=latest,enable={{is_default_branch}}
            # Tag with the short Git commit SHA
            type=sha,prefix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the repository root
          file: ./Dockerfile # Path to your Dockerfile (default is ./Dockerfile)
          push: true # Actually push the image
          tags: ${{ steps.meta.outputs.tags }} # Use tags generated by the metadata action
          labels: ${{ steps.meta.outputs.labels }} # Use labels generated by the metadata action
          cache-from: type=gha # Enable build cache from GitHub Actions cache
          cache-to: type=gha,mode=max # Enable writing build cache to GitHub Actions cache